// prettier-ignore
/* eslint-disable */
/* generated by @solid-hooks/i18n vite plugin */
type ParseMessage<T> = {
  [K in string]: () => Promise<T>
}

export type MSG = ParseMessage<{
  "test": string,
  "asd": string,
  "plural": "{name}_{num}()",
  "test2": string,
  "test3": string,
  "nest": {
    "description": string,
    "variable": "{variable}"
  }
}>
